# Generated by Django 3.1.1 on 2020-10-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_num', models.IntegerField()),
                ('apartment_num', models.IntegerField()),
                ('common_due', models.CharField(max_length=5)),
                ('elevator_due', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['floor_num', 'apartment_num'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeland_manager.apartment')),
            ],
            options={
                'ordering': ['apartment', 'names'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_common', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_elevator', models.CharField(blank=True, max_length=10, null=True)),
                ('monthly_given', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('a', 'Awaiting for payment'), ('m', 'Missed payment'), ('p', 'Payed'), ('s', 'Skip')], default='a', help_text='monthly bills information', max_length=1)),
                ('due_apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeland_manager.apartment')),
                ('due_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeland_manager.paymentdate')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_tax', models.IntegerField(blank=True, null=True)),
                ('elevator_electricity', models.CharField(blank=True, max_length=10, null=True)),
                ('elevator_additional', models.CharField(blank=True, max_length=10, null=True)),
                ('elevator_comment', models.CharField(blank=True, max_length=30, null=True)),
                ('bill_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeland_manager.paymentdate')),
            ],
            options={
                'ordering': ['bill_date'],
            },
        ),
        migrations.CreateModel(
            name='CommonDue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner_tax', models.IntegerField(blank=True, null=True)),
                ('stairs_electricity', models.CharField(blank=True, max_length=10, null=True)),
                ('other_payments', models.CharField(blank=True, max_length=10, null=True)),
                ('other_comment', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeland_manager.paymentdate')),
            ],
        ),
    ]
