# Generated by Django 3.1.1 on 2020-11-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeland_manager', '0002_auto_20201115_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='common_due',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='elevator_due',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='commondue',
            name='other_comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='commondue',
            name='other_payments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commondue',
            name='stairs_electricity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevatordue',
            name='elevator_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevatordue',
            name='elevator_comment',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='elevatordue',
            name='elevator_electricity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='monthly_common',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='monthly_elevator',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='monthly_given',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlydue',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Awaiting for payment'), ('m', 'Missed payment'), ('p', 'Payed'), ('s', 'Skip')], default='a', help_text='monthly bills information', max_length=1),
        ),
        migrations.AlterField(
            model_name='owner',
            name='names',
            field=models.CharField(max_length=30),
        ),
    ]
